### PR TITLE
Add Cakey Bot as All-in-One bot option

### PR DESCRIPTION
**Pull request by MrCakeSlayer**

### CODE REVIEW

**Comment by MrCakeSlayer** [comment]
As a side note, I also noticed a few _consistency_ issues across several pages. I fixed a couple in this PR, however, I'll probably make a proper second PR to address those later since they don't really fall within the scope of this PR.

**Comment by NotDemonix** [comment]
bro moved other bots down and put his higher 💀

**Comment by realCmdData** [comment]
Please make seperate Pull Requests for each page edited since merging one Pull Request will force updating every commit made in this PR.

**Comment by MrCakeSlayer** [comment]
@NotDemonix I placed it at the bottom of each list except in cases where the last bot made specific me tion of "other bots above this one" or on the one page re where the bottom one was an "anti-alternative". Which seemed the most logical imo

@realCmdData just to confirm, you want me to spam 11 separate PRs to add a single bot? That seems a bit excessive?

**Comment by realCmdData** [comment]
@MrCakeSlayer Yes, since each section should be treated differently. Unless you're only editing minor spelling mistakes I would prefer it like that so I can better keep an overview where each bot can be added. 
And as Demonix pointed it, if you are going to add your own bot, add it to the bottom of the list and if the wording of the above bots don't match you can obviously also fix that aswell.

As a side note aswell, it's not feasible nor entirely fair to essentially advertise one bot on 11 different categories, which is why the All in One replacement category exists. Duplicates only exist because it's a small category or one where there just aren't any better/trustworthy/well-known alternatives.

**Comment by MrCakeSlayer** [comment]
> As a side note aswell, it's not feasible nor entirely fair to essentially advertise one bot on 11 different categories,
I can see how it would be portrayed as advertising, however, I felt it was most accurate to list the bot on the feature pages that were included in the bot. I've instead pushed only the primary features of the bot instead or on pages that had few alternatives.

**Pull request closed without merging**
